const inputRange1 = [
  {
    label: "Date Manufactured",
    defaultValueForPicker: "",
    value: sheetEq?.date_manufactured, //Raw data should be formated in the component
    type: "date",
    length: null,
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: true, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "date_manufactured",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Cable Starting Point",
    value: sheetEq?.cable_starting_point,
    type: "text",
    length: null,
    defaultValueForPicker: "", //unit prop
    picker: null, //unit prop
    pickerOptions: null, //unit prop
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "cable_starting_point",
    unitProperty: null, //unit prop
    table: "Sheet",
  },
  {
    label: "Cable Ending Point",
    value: sheetEq?.cable_ending_point,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "cable_ending_point",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Starting Termination Type",
    value: sheetEq?.cable_starting_termination_type,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "cable_starting_termination_type",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Ending Termination Type",
    value: sheetEq?.cable_ending_termination_type,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "cable_ending_termination_type",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Conductor Material",
    value: sheetEq?.cable_conductor_material,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "cable_conductor_material",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Conductor Size",
    value: sheetEq?.cable_size,
    type: "numeric",
    length: 5,
    defaultValueForPicker: sheetEq?.cable_size_units,
    picker: "select",
    pickerOptions: {
      PAS: "MCM",
      option2: "/0 AWG",
    },
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "cable_size",
    unitProperty: "cable_size_units",
    table: "Sheet",
  },
  {
    label: "Insulation Material",
    value: sheetEq?.cable_insulation_material,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "cable_insulation_material",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Insulation Thickness",
    value: sheetEq?.cable_insulation_thickness,
    type: "numeric",
    length: 5,
    defaultValueForPicker: sheetEq?.cable_insulation_thickness_units,
    picker: "select",
    pickerOptions: {
      PAS: "mils",
      option2: "mm",
    },
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "cable_insulation_thickness",
    unitProperty: "cable_insulation_thickness_units",
    table: "Sheet",
  },
  {
    label: "Cable Length",
    value: sheetEq?.cable_length,
    type: "numeric",
    length: 12,
    defaultValueForPicker: sheetEq?.cable_length_units,
    picker: "select",
    pickerOptions: {
      PAS: "feet",
      option2: "meters",
    },
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "cable_length",
    unitProperty: "cable_length_units",
    table: "Sheet",
  },
  {
    label: "Operating Voltage(kV)",
    value: sheetEq?.operating_cable_voltage,
    type: "numeric",
    length: 12,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "operating_cable_voltage",
    unitProperty: null,
    table: "Sheet",
  },

  {
    label: "Cable Volt Rating(kV)",
    value: sheetEq?.cable_voltage_rating,
    type: "numeric",
    length: 12,
    defaultValueForPicker: "",
    picker: "select",
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "cable_voltage_rating",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Insulation Rating", // NOTE: This field is a picker ONLY.
    value: null,
    type: "numeric",
    length: 3,
    defaultValueForPicker: sheetEq?.cable_insulation_rating,
    picker: "select",
    pickerOptions: {
      PAS: "100",
      option2: "133",
      option3: "173",
    },
    placeholder: null,
    custom: false,
    visible: eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: null,
    unitProperty: "cable_insulation_rating",
    table: "Sheet",
  },
  {
    label: "Max Voltage",
    value: sheetEq?.equipment_voltage,
    type: "numeric",
    length: 12,
    defaultValueForPicker: "insert below conditional value",
    //   if (sheetEq?.is_dc_equipment_voltage) {
    //     "DC"
    //   } else {
    //     "AC"
    //   }

    picker: "select",
    pickerOptions: {
      PAS: "AC",
      option2: "DC",
    },
    placeholder: null,
    custom: false,
    visible:
      !eqType?.is_transformer ||
      !eqType?.is_cable ||
      !eqType?.is_power_meter ||
      !eqType?.is_mv_cable ||
      !eqType?.is_cpt, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "equipment_voltage",
    unitProperty: "is_dc_equipment_voltage",
    table: "Sheet",
  },
  {
    label: "System Voltage",
    value: sheetEq?.system_voltage,
    type: "text",
    length: null,
    defaultValueForPicker: "insert below conditional value",
    //   if (sheetEq?.is_dc_system_voltage) {
    //     "DC"
    //   } else {
    //     "AC"
    //   }

    picker: "select",
    pickerOptions: {
      PAS: "AC",
      option2: "DC",
    },
    placeholder: null,
    custom: false,
    visible:
      !eqType?.is_transformer ||
      !eqType?.is_cable ||
      !eqType?.is_power_meter ||
      !eqType?.is_mv_cable ||
      !eqType?.is_cpt, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "system_voltage",
    unitProperty: "is_dc_system_voltage",
    table: "Sheet",
  },
  // {
  //   label: "Interrupting Capacity",
  //   value: sheetEq?.PROPERTY_VALUEXXXXXXXXXXXX,
  //   type: "text",
  //   length: null,
  //   defaultValueForPicker: "",
  //   picker: null,
  //   pickerOptions: null,
  //   placeholder: null,
  //   custom: false,
  //   visible: !eqType?.is_transformer, // Conditions for visibility of particular property
  //   customComponent: null,
  //   moldProperty: true,
  //   property: "PROPERTY_VALUEXXXXXXXXXXXX",
  //   unitProperty: null,
  //   table: "Sheet",
  // },
  {
    label: "Interrupting Capacity",
    value: sheetEq?.interrupting_capacity && sheetEq?.interrupting_voltage, //SEE INTERRUPTING CAPACITY ON LOW VOLTAGE POWER CIRCUIT BREAKER
    type: "both numeric",
    length: "both 12",
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: true,
    visible: eqType?.is_breaker && !eqType?.is_mv_or_hv_breaker, // Conditions for visibility of particular property
    customComponent: someCustomeComponenet(),
    moldProperty: true,
    property: "interrupting_capacity && interrupting_voltage",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "",
    //   if (sheetEq?.is_dc_system_voltage) {
    //     "Continuous Amp Rating"
    //   } elif {
    //     "Frame Size"
    //   }
    //    else {
    //     "Amp Rating"
    //   }
    value: sheetEq?.frame_size,
    type: "numeric",
    length: 12,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: true, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "frame_size",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Mount Style",
    value: sheetEq?.mount_style,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: !eqType?.is_mv_or_hv_breaker && eqType?.is_breaker, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "mount_style",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Control Voltage",
    value: sheetEq?.control_voltage,
    type: "numeric",
    length: 12,
    defaultValueForPicker: () => {
      if (sheetEq?.is_dc_control_voltage) {
        ("DC");
      } else {
        ("AC");
      }
    },
    // if sheetEq?.is_dc_control_voltage
    // "DC"
    // else
    // "AC"
    picker: "select",
    pickerOptions: {
      PAS: "AC",
      option2: "DC",
    },
    placeholder: null,
    custom: false,
    visible: !eqType?.is_cable, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "control_voltage",
    unitProperty: "is_dc_control_voltage",
    table: "Sheet",
  },
  {
    label: "Trip Coil Voltage",
    value: sheetEq?.trip_coil_voltage,
    type: "numeric",
    length: 12,
    defaultValueForPicker: () => {
      if (sheetEq?.is_dc_trip_voltage) {
        ("DC");
      } else {
        ("AC");
      }
    },
    // if sheetEq?.is_dc_control_voltage
    // "DC"
    // else
    // "AC"
    picker: "select",
    pickerOptions: {
      PAS: "AC",
      option2: "DC",
    },
    placeholder: null,
    custom: false,
    visible: eqType?.is_breaker, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "trip_coil_voltage",
    unitProperty: "is_dc_trip_voltage",
    table: "Sheet",
  },
  {
    label: "Fuse Manufacturer",
    value: sheetEq?.fuse_manufacturer,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_power_fused, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "fuse_manufacturer",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Fuse Type",
    value: sheetEq?.fuse_type,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_power_fused, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "fuse_type",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Fuse Size (Amps)",
    value: sheetEq?.fuse_size,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_power_fused, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "fuse_size",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Operations Count As Found",
    value: sheetEq?.operations_counter_af,
    type: "numeric",
    length: 8,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType.is_op_counter, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: false,
    property: "operations_counter_af",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Operations Count As Left",
    value: sheetEq?.operations_counter_al,
    type: "numeric",
    length: 8,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType.is_op_counter, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: false,
    property: "operations_counter_al",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Trip Unit Manufacturer",
    value: sheetEq?.trip_unit_manufacturer,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_trip_unit && sheetEq.is_trip_unit, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "trip_unit_manufacturer",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Trip Unit Model",
    value: sheetEq?.trip_unit_model,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_trip_unit && sheetEq.is_trip_unit, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "trip_unit_model",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Trip Unit Serial Number",
    value: sheetEq?.trip_unit_serial_number,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_trip_unit && sheetEq.is_trip_unit, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "trip_unit_serial_number",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Rating Plug (amps)",
    value: sheetEq?.trip_unit_rating_plug,
    type: "numeric",
    length: 12,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_trip_unit && sheetEq.is_trip_unit, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "trip_unit_rating_plug",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Trip Unit Curve",
    value: sheetEq?.trip_unit_curve,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_trip_unit && sheetEq.is_trip_unit, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "trip_unit_curve",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Phase CT Ratio (amps)",
    value: sheetEq?.trip_unit_phase_ct_high && sheetEq?.trip_unit_phase_ct_low,
    type: "number",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: true,
    visible: eqType?.is_transformer, // Conditions for visibility of particular property
    customComponent: someCustomeComponenet(),
    moldProperty: true,
    property: "trip_unit_phase_ct_high" && "trip_unit_phase_ct_low",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Primary Voltage",
    value: sheetEq?.primary_voltage,
    type: "numeric",
    length: 12,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "primary_voltage",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Secondary Voltage",
    value: sheetEq?.secondary_voltage,
    type: "numeric",
    length: 12,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "secondary_voltage",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Power Rating",
    value: sheetEq?.power_rating,
    type: "numeric",
    length: 12,
    defaultValueForPicker: sheetEq?.power_rating_units,
    picker: "select",
    pickerOptions: {
      PAS: "VA",
      option2: "KVA",
      option2: "MVA",
    },
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "power_rating",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Primary Configuration",
    value: sheetEq?.primary_winding_config,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "primary_winding_config",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Secondary Configuration",
    value: sheetEq?.secondary_winding_config,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "secondary_winding_config",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Weight",
    value: sheetEq?.weight,
    type: "numeric",
    length: 12,
    defaultValueForPicker: sheetEq?.weight_units,
    picker: "select",
    pickerOptions: {
      PAS: "lbs",
      option2: "kg",
    },
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "weight",
    unitProperty: "weight_units",
    table: "Sheet",
  },
  {
    label: "Temperature Rise",
    value: sheetEq?.temp_rise,
    type: "numeric",
    length: 12,
    defaultValueForPicker: sheetEq?.temp_rise_units,
    picker: "select",
    pickerOptions: {
      PAS: "&#176C C",
      option2: "&#176C F",
    },
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "temp_rise",
    unitProperty: "temp_rise_units",
    table: "Sheet",
  },
  {
    label: "Impedance",
    value: sheetEq?.impedance,
    type: "numeric",
    length: 12,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "impedance",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Class",
    value: sheetEq?.xfmr_class,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "xfmr_class",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "# of Taps",
    value: sheetEq?.tap_qty,
    type: "numeric",
    length: 5,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer || eqType?.is_cpt || eqType.is_vt, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "tap_qty",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Fluid Type",
    value: sheetEq?.fluid_type,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer && !eqType?.is_liquid_type, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "fluid_type",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Fluid Capacity",
    value: sheetEq?.fluid_capacity,
    type: "numeric",
    length: 12,
    defaultValueForPicker: sheetEq?.fluid_capacity_units,
    picker: "select",
    pickerOptions: {
      PAS: "gal",
      option2: "liter",
    },
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer && !eqType?.is_liquid_type, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: true,
    property: "fluid_capacity",
    unitProperty: "fluid_capacity_units",
    table: "Sheet",
  },
  {
    label: "Fluid Level",
    value: sheetEq?.liquid_level,
    type: "text",
    length: null,
    defaultValueForPicker: "",
    picker: null,
    pickerOptions: null,
    placeholder: null,
    custom: false,
    visible: eqType?.is_transformer && !eqType?.is_liquid_type, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: false,
    property: "liquid_level",
    unitProperty: null,
    table: "Sheet",
  },
  {
    label: "Pressure",
    value: sheetEq?.pressure,
    type: "numeric",
    length: 12,
    defaultValueForPicker: sheetEq?.pressure_units,
    picker: "select",
    pickerOptions: {
      PAS: "psig",
      option2: "Mpa",
      option2: "mmhg",
      option2: "inhg",
    },
    placeholder: null,
    custom: false,
    visible: true, // Conditions for visibility of particular property
    customComponent: null,
    moldProperty: false,
    property: "pressure",
    unitProperty: "pressure_units",
    table: "Sheet",
  },
];

const contactResistanceData = [
  {
    data: [
      {
        label: "@",
        value: sheetEq?.contact_resistance_current,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker: sheetEq?.pressure_units,
        picker: "select",
        pickerOptions: {
          PAS: "psig",
          option2: "Mpa",
          option2: "mmhg",
          option2: "inhg",
        },
        visible: eqType?.is_contact_resistance,
        property: "contact_resistance_current",
        unitProperty: "pressure_units",
        unit: "Amps",
      },
      {
        label: "A",
        value: sheetEq?.contact_resistance_a,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker: sheetEq?.contact_resistance_a_units,
        picker: "select",
        pickerOptions: {
          PAS: "micro",
          option2: "micro",
        },
        visible: eqType?.is_contact_resistance,
        property: "contact_resistance_a",
        unitProperty: "contact_resistance_a_units",
        unit: "Ohms",
      },
      {
        label: "B",
        value: sheetEq?.contact_resistance_b,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker: sheetEq?.contact_resistance_b_units,
        picker: "select",
        pickerOptions: {
          PAS: "micro",
          option2: "micro",
        },
        visible: eqType?.is_contact_resistance,
        property: "contact_resistance_b",
        unitProperty: "contact_resistance_b_units",
        unit: "Ohms",
      },
      {
        label: "C",
        value: sheetEq?.contact_resistance_c,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker: sheetEq?.contact_resistance_c_units,
        picker: "select",
        pickerOptions: {
          PAS: "micro",
          option2: "micro",
        },
        options: { micro: "micro" },
        visible: eqType?.is_contact_resistance,
        property: "contact_resistance_c",
        unitProperty: "contact_resistance_c_units",
        unit: "Ohms",
      },
    ],
  },
];

const insulationResistanceData = [
  {
    data: [
      {
        label: "@",
        value: sheetEq?.insulation_resistance_ph_to_ph_test_voltage,
        inputType: "numeric",
        maxLength: 10000,
        picker: false,
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ph_to_ph_test_voltage",
        unit: "Amps",
      },
      {
        label: "A-B",
        value: sheetEq?.insulation_resistance_ph_to_ph_a_b,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker:
          sheetEq?.insulation_resistance_ph_to_ph_a_b_units,
        picker: "select",
        pickerOptions: {
          PAS: "Kilo",
          option2: "Mega",
          option2: "Giga",
          option2: "Tera",
        },
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ph_to_ph_a_b",
        unitProperty: "insulation_resistance_ph_to_ph_a_b_units",
        unit: "Ohms",
      },
      {
        label: "B-C",
        value: sheetEq?.insulation_resistance_ph_to_ph_b_c,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker:
          sheetEq?.insulation_resistance_ph_to_ph_b_c_units,
        picker: "select",
        pickerOptions: {
          PAS: "Kilo",
          option2: "Mega",
          option2: "Giga",
          option2: "Tera",
        },
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ph_to_ph_b_c",
        unitProperty: "insulation_resistance_ph_to_ph_b_c_units",
        unit: "Ohms",
      },
      {
        label: "C-A",
        value: sheetEq?.insulation_resistance_ph_to_ph_c_a,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker:
          sheetEq?.insulation_resistance_ph_to_ph_c_a_units,
        picker: "select",
        pickerOptions: {
          PAS: "Kilo",
          option2: "Mega",
          option2: "Giga",
          option2: "Tera",
        },
        options: { micro: "micro" },
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ph_to_ph_c_a",
        unitProperty: "insulation_resistance_ph_to_ph_c_a_units",
        unit: "Ohms",
      },
      {
        label: "@",
        value: sheetEq?.insulation_resistance_ph_to_gr_test_voltage,
        inputType: "numeric",
        maxLength: 10000,
        picker: false,
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ph_to_gr_test_voltage",
        unit: "Amps",
      },
      {
        label: "A-G",
        value: sheetEq?.insulation_resistance_ph_to_gr_a_g,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker:
          sheetEq?.insulation_resistance_ph_to_gr_a_g_units,
        picker: "select",
        pickerOptions: {
          PAS: "Kilo",
          option2: "Mega",
          option2: "Giga",
          option2: "Tera",
        },
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ph_to_gr_a_g",
        unitProperty: "insulation_resistance_ph_to_gr_a_g_units",
        unit: "Ohms",
      },
      {
        label: "B-G",
        value: sheetEq?.insulation_resistance_ph_to_gr_b_g,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker:
          sheetEq?.insulation_resistance_ph_to_gr_b_g_units,
        picker: "select",
        pickerOptions: {
          PAS: "Kilo",
          option2: "Mega",
          option2: "Giga",
          option2: "Tera",
        },
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ph_to_gr_b_g",
        unitProperty: "insulation_resistance_ph_to_gr_b_g_units",
        unit: "Ohms",
      },
      {
        label: "C-G",
        value: sheetEq?.insulation_resistance_ph_to_gr_c_g,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker:
          sheetEq?.insulation_resistance_ph_to_gr_c_g_units,
        picker: "select",
        pickerOptions: {
          PAS: "Kilo",
          option2: "Mega",
          option2: "Giga",
          option2: "Tera",
        },
        options: { micro: "micro" },
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ph_to_gr_c_g",
        unitProperty: "insulation_resistance_ph_to_gr_c_g_units",
        unit: "Ohms",
      },
      {
        label: "@",
        value: sheetEq?.insulation_resistance_ln_to_ld_test_voltage,
        inputType: "numeric",
        maxLength: 10000,
        picker: false,
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ln_to_ld_test_voltage",
        unit: "Amps",
      },
      {
        label: "A-A&apos;",
        value: sheetEq?.insulation_resistance_ln_to_ld_a,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker: sheetEq?.insulation_resistance_ln_to_ld_a_units,
        picker: "select",
        pickerOptions: {
          PAS: "Kilo",
          option2: "Mega",
          option2: "Giga",
          option2: "Tera",
        },
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ln_to_ld_a",
        unitProperty: "insulation_resistance_ln_to_ld_a_units",
        unit: "Ohms",
      },
      {
        label: "B-B&apos;",
        value: sheetEq?.insulation_resistance_ln_to_ld_b,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker: sheetEq?.insulation_resistance_ln_to_ld_b_units,
        picker: "select",
        pickerOptions: {
          PAS: "Kilo",
          option2: "Mega",
          option2: "Giga",
          option2: "Tera",
        },
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ln_to_ld_b",
        unitProperty: "insulation_resistance_ln_to_ld_b_units",
        unit: "Ohms",
      },
      {
        label: "C-C&apos;",
        value: sheetEq?.insulation_resistance_ln_to_ld_c,
        inputType: "numeric",
        maxLength: 10000,
        defaultValueForPicker: sheetEq?.insulation_resistance_ln_to_ld_c_units,
        picker: "select",
        pickerOptions: {
          PAS: "Kilo",
          option2: "Mega",
          option2: "Giga",
          option2: "Tera",
        },
        options: { micro: "micro" },
        visible: eqType?.is_insulation_resistance,
        property: "insulation_resistance_ln_to_ld_c",
        unitProperty: "insulation_resistance_ln_to_ld_c_units",
        unit: "Ohms",
      },
    ],
  },
];

const hipotData = [
  {
    title: "phase-to-phase",
    visible: !eqType?.is_switchgear,
  },
  {
    data: [
      {
        label: "A-B",
        value: sheetEq?.hipot_ptp_ab,
        inputType: "numeric",
        maxLength: 10000,
        property: "hipot_ptp_ab",
        visible: eqType?.is_hipot || !eqType?.is_switchgear,
        unit: "miliAmps",
      },
      {
        label: "B-C",
        value: sheetEq?.hipot_ptp_bc,
        inputType: "numeric",
        maxLength: 10000,
        property: "hipot_ptp_bc",
        visible: eqType?.is_hipot || !eqType?.is_switchgear,
        unit: "miliAmps",
      },
      {
        label: "C-A",
        value: sheetEq?.hipot_ptp_ca,
        inputType: "numeric",
        maxLength: 10000,
        property: "hipot_ptp_ca",
        visible: eqType?.is_hipot || !eqType?.is_switchgear,
        unit: "miliAmps",
      },
    ],
  },
  {
    title: "phase-to-ground",
    visible: true,
  },
  {
    data: [
      {
        label: "A-G",
        value: sheetEq?.hipot_ptg_a,
        inputType: "numeric",
        maxLength: 10000,
        property: "hipot_ptg_a",
        visible: eqType?.is_hipot,
        unit: "miliAmps",
      },
      {
        label: "B-G",
        value: sheetEq?.hipot_ptg_b,
        inputType: "numeric",
        maxLength: 10000,
        property: "hipot_ptg_b",
        visible: eqType?.is_hipot,
        unit: "miliAmps",
      },
      {
        label: "C-G",
        value: sheetEq?.hipot_ptg_c,
        inputType: "numeric",
        maxLength: 10000,
        property: "hipot_ptg_c",
        visible: eqType?.is_hipot,
        unit: "miliAmps",
      },
    ],
  },
  {
    title: "line-to-load",
    visible: !eqType?.is_switchgear,
  },
  {
    data: [
      {
        label: "A-A&apos;",
        value: sheetEq?.hipot_ltl_a,
        inputType: "numeric",
        maxLength: 10000,
        property: "hipot_ltl_a",
        visible: eqType?.is_hipot || !eqType?.is_switchgear,
        unit: "miliAmps",
      },
      {
        label: "B-B&apos;",
        value: sheetEq?.hipot_ltl_b,
        inputType: "numeric",
        maxLength: 10000,
        property: "hipot_ltl_b",
        visible: eqType?.is_hipot || !eqType?.is_switchgear,
        unit: "miliAmps",
      },
      {
        label: "C-C&apos;",
        value: sheetEq?.hipot_ltl_c,
        inputType: "numeric",
        maxLength: 10000,
        property: "hipot_ltl_c",
        visible: eqType?.is_hipot || !eqType?.is_switchgear,
        unit: "miliAmps",
      },
    ],
  },
];
