from django.contrib import admin
from .models import Type, Manufacturer, BusContactTestData, Model, ModelNotes, WorkingNote, ModelFolder, UserProperties, Equipment, EquipmentFolder, Job, JobFolder, TestEquipment, JobNotes, EquipmentNotes, CableTestData, EquipmentLink, TypeNotes, TypeFolder, TypeTestStandards, TypeTestGuide, ModelTestGuide, JobSite, JobSiteNotes, JobSiteFolder, Company, FeedbackFile, FeedbackNote, TestSheet, Well, WellNotes, MaintEvent, MaintFile, MaintNotes, GenericFile, GenericNote, SupportOffer, SupportSession, SupportRequest, ScopeItem, ScopeTask, SafetySheet, SafetyHazard, LotoDescription, SafetyBoolean, Signature



# Register your models here.
admin.site.register(Type)
admin.site.register(Manufacturer)
admin.site.register(Model)
admin.site.register(ModelNotes)
admin.site.register(ModelFolder)
admin.site.register(Equipment)
admin.site.register(EquipmentFolder)
admin.site.register(EquipmentLink)
admin.site.register(Job)
admin.site.register(JobFolder)
admin.site.register(TestEquipment)
admin.site.register(UserProperties)
admin.site.register(JobNotes)
admin.site.register(EquipmentNotes)
admin.site.register(TypeFolder)
admin.site.register(TypeNotes)
admin.site.register(TypeTestStandards)
admin.site.register(TypeTestGuide)
admin.site.register(ModelTestGuide)
admin.site.register(JobSite)
admin.site.register(JobSiteNotes)
admin.site.register(JobSiteFolder)
admin.site.register(Company)
admin.site.register(FeedbackNote)
admin.site.register(FeedbackFile)
admin.site.register(TestSheet)
admin.site.register(CableTestData)
admin.site.register(WorkingNote)
admin.site.register(Well)
admin.site.register(WellNotes)
admin.site.register(MaintEvent)
admin.site.register(MaintFile)
admin.site.register(MaintNotes)
admin.site.register(BusContactTestData)
admin.site.register(SupportRequest)
admin.site.register(SupportOffer)
admin.site.register(SupportSession)
admin.site.register(GenericFile)
admin.site.register(GenericNote)
admin.site.register(ScopeItem)
admin.site.register(ScopeTask)
admin.site.register(SafetySheet)
admin.site.register(SafetyHazard)
admin.site.register(LotoDescription)
admin.site.register(SafetyBoolean)
admin.site.register(Signature)