# Generated by Django 3.0.6 on 2021-08-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0110_auto_20210803_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='job_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_jobsite', to='tracker.JobSite'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='parent_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_eq', to='tracker.Equipment'),
        ),
    ]
