# Generated by Django 3.0.6 on 2021-10-24 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0111_auto_20210808_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_mold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casting', to='tracker.Equipment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_testing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipmentnotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentnotes',
            name='parent_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_notes', to='tracker.EquipmentNotes'),
        ),
        migrations.AddField(
            model_name='equipmentnotes',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_equipment_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='test_equipment',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='tracker.TestEquipment'),
        ),
        migrations.AddField(
            model_name='jobnotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobnotes',
            name='parent_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_notes', to='tracker.JobNotes'),
        ),
        migrations.AddField(
            model_name='jobnotes',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_job_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='modelnotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelnotes',
            name='parent_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_notes', to='tracker.ModelNotes'),
        ),
        migrations.AddField(
            model_name='modelnotes',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_model_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='equipment_voltage',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='is_dc_equipment_voltage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='type',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='typenotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typenotes',
            name='parent_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_notes', to='tracker.TypeNotes'),
        ),
        migrations.AddField(
            model_name='typenotes',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_type_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeteststandards',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_test_standard', to='tracker.UserProperties'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='parent_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_equipments', to='tracker.Equipment'),
        ),
        migrations.AlterField(
            model_name='testsheet',
            name='eq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_eq', to='tracker.Equipment'),
        ),
    ]
