# Generated by Django 3.0.6 on 2021-10-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0112_auto_20211024_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
