# Generated by Django 3.0.6 on 2022-01-15 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0115_auto_20220115_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentfolder',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_eq_file', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobsitenotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
