# Generated by Django 3.2 on 2022-11-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0121_auto_20220426_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='selected_tab',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
