# Generated by Django 3.2 on 2022-12-05 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0122_equipment_selected_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eq_session', to='tracker.equipment')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester_session', to=settings.AUTH_USER_MODEL)),
                ('supporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporter_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
