# Generated by Django 3.2 on 2022-12-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0125_auto_20221210_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportrequest',
            old_name='name',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='summary',
        ),
    ]
