# Generated by Django 3.2 on 2023-01-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0126_auto_20221222_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
