# Generated by Django 3.2 on 2023-01-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0128_auto_20230129_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
