# Generated by Django 4.1.2 on 2023-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0129_alter_supportrequest_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportsession",
            name="meeting_link",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
